name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      # Runs a set of commands using the runners shell
      - name: build all
        run: |
          pushd demo
          ./ng all
          popd
      - name: test simple debug
        run: demo/_out/linux/demo_simple_debug
      - name: test simple release
        run: demo/_out/linux/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/linux/demo_simple_nomicroprofile
      - name: test simple lto
        run: demo/_out/linux/demo_simple_lto
      - name: test simple asan
        run: demo/_out/linux/demo_simple_asan
      - name: test simple ubsan
        run: demo/_out/linux/demo_simple_ubsan
      - name: test simple tsan
        run: demo/_out/linux/demo_simple_tsan
      - name: test simple msan
        run: demo/_out/linux/demo_simple_msan

  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      # Runs a set of commands using the runners shell
      - name: build all
        run: |
          pushd demo
          ./ng all
          popd
      - name: test simple debug
        run: demo/_out/osx/demo_simple_debug
      - name: test simple release
        run: demo/_out/osx/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/osx/demo_simple_nomicroprofile
      - name: test simple lto
        run: demo/_out/osx/demo_simple_lto
      - name: test simple asan
        run: demo/_out/osx/demo_simple_asan
      - name: test simple ubsan
        run: demo/_out/osx/demo_simple_ubsan
      - name: test simple tsan
        run: demo/_out/osx/demo_simple_tsan


  build-windows:
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      # Runs a set of commands using the runners shell
      - name: build all
        run: |
          pushd demo
          dir
          ./ng.bat all
          popd
      - name: test simple debug
        run: demo/_out/win32/demo_simple_debug
      - name: test simple release
        run: demo/_out/win32/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/win32/demo_simple_nomicroprofile
